export const ADMIN_STATS_REQUEST = "ADMIN_STATS_REQUEST"
export const ADMIN_STATS_SUCCESS = "ADMIN_STATS_SUCCESS"
export const ADMIN_STATS_FAIL = "ADMIN_STATS_FAIL"

export const ADMIN_INFLUENCERS_REQUEST = "ADMIN_INFLUENCERS_REQUEST"
export const ADMIN_INFLUENCERS_SUCCESS = "ADMIN_INFLUENCERS_SUCCESS"
export const ADMIN_INFLUENCERS_FAIL = "ADMIN_INFLUENCERS_FAIL"

export const ADMIN_BUSINESSES_REQUEST = "ADMIN_BUSINESSES_REQUEST"
export const ADMIN_BUSINESSES_SUCCESS = "ADMIN_BUSINESSES_SUCCESS"
export const ADMIN_BUSINESSES_FAIL = "ADMIN_BUSINESSES_FAIL"

export const VERIFICATION_REQUESTS_REQUEST = "VERIFICATION_REQUESTS_REQUEST"
export const VERIFICATION_REQUESTS_SUCCESS = "VERIFICATION_REQUESTS_SUCCESS"
export const VERIFICATION_REQUESTS_FAIL = "VERIFICATION_REQUESTS_FAIL"

export const VERIFICATION_UPDATE_REQUEST = "VERIFICATION_UPDATE_REQUEST"
export const VERIFICATION_UPDATE_SUCCESS = "VERIFICATION_UPDATE_SUCCESS"
export const VERIFICATION_UPDATE_FAIL = "VERIFICATION_UPDATE_FAIL"
export const VERIFICATION_UPDATE_RESET = "VERIFICATION_UPDATE_RESET"
