export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST"
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS"
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL"

export const CHAT_DETAILS_REQUEST = "CHAT_DETAILS_REQUEST"
export const CHAT_DETAILS_SUCCESS = "CHAT_DETAILS_SUCCESS"
export const CHAT_DETAILS_FAIL = "CHAT_DETAILS_FAIL"

export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST"
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS"
export const MESSAGE_SEND_FAIL = "MESSAGE_SEND_FAIL"
export const MESSAGE_SEND_RESET = "MESSAGE_SEND_RESET"

export const NEW_MESSAGE_RECEIVED = "NEW_MESSAGE_RECEIVED"

export const CHAT_LIST_RESET = "CHAT_LIST_RESET"