export const INFLUENCER_LIST_REQUEST = "INFLUENCER_LIST_REQUEST"
export const INFLUENCER_LIST_SUCCESS = "INFLUENCER_LIST_SUCCESS"
export const INFLUENCER_LIST_FAIL = "INFLUENCER_LIST_FAIL"

export const INFLUENCER_DETAILS_REQUEST = "INFLUENCER_DETAILS_REQUEST"
export const INFLUENCER_DETAILS_SUCCESS = "INFLUENCER_DETAILS_SUCCESS"
export const INFLUENCER_DETAILS_FAIL = "INFLUENCER_DETAILS_FAIL"

export const INFLUENCER_FILTER_UPDATE = "INFLUENCER_FILTER_UPDATE"


export const INFLUENCER_DETAILS_RESET = "INFLUENCER_DETAILS_RESET"