export const BUSINESS_VERIFICATION_REQUEST = "BUSINESS_VERIFICATION_REQUEST";
export const BUSINESS_VERIFICATION_SUCCESS = "BUSINESS_VERIFICATION_SUCCESS";
export const BUSINESS_VERIFICATION_FAIL = "BUSINESS_VERIFICATION_FAIL";

export const BUSINESS_VERIFICATION_STATUS_REQUEST = "BUSINESS_VERIFICATION_STATUS_REQUEST";
export const BUSINESS_VERIFICATION_STATUS_SUCCESS = "BUSINESS_VERIFICATION_STATUS_SUCCESS";
export const BUSINESS_VERIFICATION_STATUS_FAIL = "BUSINESS_VERIFICATION_STATUS_FAIL";

export const VERIFICATION_LIST_REQUEST = "VERIFICATION_LIST_REQUEST";
export const VERIFICATION_LIST_SUCCESS = "VERIFICATION_LIST_SUCCESS";
export const VERIFICATION_LIST_FAIL = "VERIFICATION_LIST_FAIL";

export const VERIFICATION_UPDATE_REQUEST = "VERIFICATION_UPDATE_REQUEST";
export const VERIFICATION_UPDATE_SUCCESS = "VERIFICATION_UPDATE_SUCCESS";
export const VERIFICATION_UPDATE_FAIL = "VERIFICATION_UPDATE_FAIL";
